version: '3.8'

services:
  app1:
    build: ./backend
    environment:
      - PORT=5001  # Biến môi trường PORT=5001
    networks:
      - app-network

  app2:
    build: ./backend
    environment:
      - PORT=5002  # Biến môi trường PORT=5002
    networks:
      - app-network

  app3:
    build: ./backend
    environment:
      - PORT=5003  # Biến môi trường PORT=5003
    networks:
      - app-network

  load-balancer:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
      - ./templates:/templates
      - ./logs:/var/log/nginx/
    networks:
      - app-network
    depends_on:
      - app1
      - app2
      - app3

networks:
  app-network: